from flask_orator import jsonify
from . import trans

@trans.route('/lang.js', methods=['GET'])
def lang():
    return jsonify(
        {
            'en': {
                'form.login.required': 'Login is required',
                'form.password.required': 'Password is required',
                'password': 'Password',
                'login': 'Login',
                'logout': 'Logout',
                'title': 'SMS-gateway',
                'incomingSms': 'Incoming Sms',
                'outgoingSms': 'Outgoing Sms',
                'sendSms': 'Send Sms',
                'ussd': 'USSD',
                'sendUssd': 'Send USSD',
                'simCarts': 'SIM carts',
                'simCart': 'SIM cart',
                'addSim': 'Create SIM',
                'updateSim': 'Update SIM',
                'phone': 'Phone',
                'text': 'Text',
                'receivedAt': 'Received at',
                'errorLabel': 'Whoops!',
                'errorDescription': 'Something went wrong.',
                'notFoundLabel': 'Not found!',
                'notFoundDescription': 'No found. Try a different search term.',
                'search': 'Search...',
                'id': 'ID',
                'createdAt': 'Created at',
                'requestSentAt': 'Request sent at',
                'requestReceivedAt': 'Request received at',
                'ussdRequest': 'USSD request',
                'ussdAnswer': 'USSD answer',
                'name': 'Name',
                'balance': 'Balance',
                'edit': 'Edit',
                'sim_id': 'SIM ID of channel',
                'sim_pass': 'SIM key of channel',
                'last_live_at': 'Last activity',
                'channel_warring': 'The transmitting channel must be configured on the GoIP device. The Activity field in the channel list will show the date of the last request from device',
                'ussd_balance': 'USSD to balance check',
                'form.name.required': 'Name is required',
                'form.sim_id.required': 'SIM ID is required',
                'form.sim_pass.required': 'SIM pass is required',
                'form.phone.required': 'Phone is required',
                'form.balance_ussd.required': 'Balance is required',
                'channel_id': 'Channel ID',
                'form.channel_id.required': 'Channel ID is required',
                'form.ussd.required': 'USSD is required',
                'form.text.required': 'Text is required',
                'check_balance': 'Check',
            },
            'ru': {
                'form.login.required': 'Логин обязателен для заполнения',
                'form.password.required': 'Пароль обязателен для заполнения',
                'password': 'Пароль',
                'login': 'Вход',
                'logout': 'Выход',
                'title': 'SMS-шлюз',
                'incomingSms': 'Входящие Sms',
                'outgoingSms': 'Исходящие Sms',
                'sendSms': 'Отправить Sms',
                'ussd': 'USSD',
                'sendUssd': 'Отправить USSD',
                'simCarts': 'SIM карты',
                'simCart': 'SIM карта',
                'addSim': 'Добавить SIM',
                'updateSim': 'Изменить SIM',
                'phone': 'Телефон',
                'text': 'Текст',
                'receivedAt': 'Дата получения',
                'errorLabel': 'Упс!',
                'errorDescription': 'Что-то пошло не так.',
                'notFoundLabel': 'Не найдено!',
                'notFoundDescription': 'Не найдено. Попробуйте другой поисковый запрос.',
                'search': 'Поиск...',
                'id': 'ID',
                'createdAt': 'Дата создания',
                'requestSentAt': 'Запрос отправлен',
                'requestReceivedAt': 'Запрос получен',
                'ussdRequest': 'USSD запрос',
                'ussdAnswer': 'USSD ответ',
                'name': 'Название',
                'balance': 'Баланс',
                'edit': 'Изменить',
                'sim_id': 'SIM ID канала',
                'sim_pass': 'SIM ключ канала',
                'last_live_at': 'Последняя активность',
                'channel_warring': 'Передающий канал должен быть настроен на GoIP устройстве. Поле активность в списке каналов покажет дату последнего запроса с утройства',
                'ussd_balance': 'USSD проверки баланса',
                'form.name.required': 'Название обязательно для заполнения',
                'form.sim_id.required': 'ID обязателен для заполнения',
                'form.sim_pass.required': 'Ключ обязателен для заполнения',
                'form.phone.required': 'Телефон обязателен для заполнения',
                'form.balance_ussd.required': 'USSD проверки баланса обязателен для заполнения',
                'channel_id': 'ID канала',
                'form.channel_id.required': 'ID канала обязателен для заполнения',
                'form.ussd.required': 'USDD обязателен для заполнения',
                'form.text.required': 'Текст обязателен для заполнения',
                'check_balance': 'Проверить',
            }
        }
    )